 version: '2'

 services:
      mysql:
          image: mysql:5.6.33
          ports:
              - "13306:3306"
          environment:
              MYSQL_ROOT_PASSWORD: sapass
              MYSQL_DATABASE: SpringWorkout


      springworkout:
          image: muzir/springworkout:0.1
          ports:
             - "8080:8080"
          depends_on:
                  - mysql
          environment:
              spring.datasource.url: jdbc:mysql://mysql/SpringWorkout?characterEncoding=UTF-8
              spring.datasource.username: root
              spring.datasource.password: sapass